const actionTypes = {
    GET_HOME: "GET_HOME",
    SET_CUR_SONG_ID: "SET_CUR_SONG_ID",
    BUY_PRODUCT: "BUY_PRODUCT",
    ADD_PRODUCT: "ADD_PRODUCT",
    ADD_STORE: "ADD_STORE",
    ADD_USER: "ADD_USER",
    ADD_DETAILBILL: "ADD_DETAILBILL",
    ADD_CART: "ADD_CART",
    ADD_MATERIAL: "ADD_MATERIAL",
    REMOVE_CART: "REMOVE_CART",
    CHANGE_STATUS: "CHANGE_STATUS",
}

export default actionTypes